### PR TITLE
Feat/support gzipped files and add test cases

### PR DESCRIPTION
**Pull request by taoliu**
I have added a `universal_open` function in `scATAC_utility.py`. It will first check if the file is gzipped if so it will use `gzip.open` (text mode) to open the file, otherwise, it will use the general `open` to open the file. I modified `scATAC_10x_PeakCount.py`, `scATAC_Genescore.py`, and `scATAC_10x_BarcodeCorrect.py` to support gzipped files as input. I haven't checked if other scripts also need to be modified to support the gzipped file. 

Also, I have set up a testing script as an example for future automatic testing under TravisCI (or other CICD). The script and testing data are at the `test` subdirectory. Currently, I only tested `MAESTRO scatac-peakcount` subcommand on the gzip files for this PR. But the concept should be able to be applied to other functions. A minimal testing case data and the standard output have been added to the `test` directory. The minimal data only contains 100 barcodes and the reads mapped to chr22 of the human genome.

The TravisCI yml code:
https://github.com/taoliu/MAESTRO/blob/4ac7361481c46fb53183b1079999b0f5266b4410/.travis.yml#L87-L90

Th test.sh code:
https://github.com/taoliu/MAESTRO/blob/4ac7361481c46fb53183b1079999b0f5266b4410/test/test.sh#L17

PS: I fixed the default option issue for `scATAC_10x_PeakCount.py` script, related to PR #43. However, I didn't fix the similar issue in other scripts.

### CODE REVIEW

**Comment by crazyhottommy** [comment]
Thanks Tao! merge it now. now we need a small test dataset for other functions.

**Comment by taoliu** [comment]
@crazyhottommy  Thanks! The output h5 file from the `peakcount` test should be able to be used in other tests.

https://github.com/liulab-dfci/MAESTRO/blob/master/test/standard_output/test_peak_count.h5

**Comment by crazyhottommy** [comment]
wired, I had a build error. but the check passed...

**Comment by crazyhottommy** [comment]
related to conda https://travis-ci.com/github/liulab-dfci/MAESTRO/builds/176387821

**Comment by crazyhottommy** [comment]
build passed :)

**Pull request merged**
