### PR TITLE
Fix/lisa update

### PR DESCRIPTION
**Pull request by DongqingSun96**
Update LISA v1.0 to v2.0

### CODE REVIEW

**Comment by taoliu** [comment]
Thanks! We may need to package the new lisa into MAESTRO conda release as well.

**Comment by DongqingSun96** [comment]
I need to check if the LISA dependencies are compatible with our current MAESTRO environment.

**Review by taoliu — APPROVED** [review]
We don't have testing for lisa in travis, so I am not sure if lisa v2 would generate the same or the different results...

**Comment by taoliu** [comment]
> I need to check if the LISA dependencies are compatible with our current MAESTRO environment.

Thanks!

**Comment by crazyhottommy** [comment]
@DongqingSun Is the problem of LISA2 fixed after you talk with Allen? @baigal628 you may want to check how Dongqing made the LISA2 changes in MAESTRO.

**Comment by crazyhottommy** [comment]
Let's merge this first. Gali will test LISA2 inside MAESTRO env.

**Pull request merged**
