### PR TITLE
Fix/conda: Fix installation issue related to conda and R devtools install. Refine CICD.

### PR DESCRIPTION
**Pull request by taoliu**
This PR addresses the following issues:

1. Building the MAESTRO conda package. The previous conda configuration contains a bug where the `r-base` version was **3.6.2** with 'build' and **3.6.2** with 'run'.  Also, while building conda package, a single `setup.py` script will be used to install many tools/dependencies including all third party tools and R packages. This will leave many dependencies out of control. To solve this issue, I have removed `MAESTRO_install.R` and other system calls within `setup.py`. Instead, all R dependencies will only be controlled through conda `meta.yml` (if the package is available through anaconda), and `DESCRIPTION` ( if the package is not available in anaconda then it will be put into the `remote` section) file which will be used with `devtools::install` in `build.sh`; all Python dependencies will only be controlled through `meta.yml`. The third-party tools including `giggle`, `rabit` and `sinto` will be controlled in `build.sh` script

2. The previous CICD won't actually test the codes related to current PR or `push` because it will install a compiled package `maestro` from anaconda. And that `conda/MAESTRO/meta.yaml` file contains a hard-code path to https://github.com/chenfeiwang/MAESTRO.git so `conda build` in fact won't build a package from current codes at all.  I modified the `travis.yml` and `meta.yml` to **build a conda package in a local channel** then ** install maestro from the local channel** so the test will reflect the actual code changes in the repository.

3. The previous CICD  will only test the `conda` installation, I have added some scripts after `build` step in `travis.yml` to test the command lines and loading libraries in R. These will make sure that after **installing** MAESTRO conda package, these commands can be called. However, since we don't have testing cases, I can't test if the MAESTRO pipeline can process data without error.

NOTE: ~~I will update this PR regularly until the travis CI test is passed,~~ I got the test passed in the 21st trial 🙈  please check: https://travis-ci.com/github/taoliu/MAESTRO

NOTE2: Could you enable travis CI in this repository?? We need the owner of this repository to set it up.

### CODE REVIEW

**Comment by crazyhottommy** [comment]
Hi Tao, thanks for fixing it. I saw "The job exceeded the maximum time limit for jobs, and has been terminated." so has not passed the test yet?

**Comment by taoliu** [comment]
@crazyhottommy Not yet! The install_git took too long. I need to do something to let it skip installing the dependencies since most of the dependencies have been installed through conda already.

**Comment by DongqingSun96** [comment]
@taoliu Hi Tao, if I change the 'run' r-base from 3.6.2 to 3.6.3, conflicts in R packages may occur during `conda build`. Have you ever encountered the problem? By the way, since MAESTRO `conda` has included the MAESTRO R package, there's no need to install R package through `devtools:install_github` in the `conda` environment.

**Comment by taoliu** [comment]
@DongqingSun96 I didn't check that! So currently, just one installation is enough? OK. Then I will remove the changes related to "3)".  No wonder that's so many duplications on dependencies.

**Comment by DongqingSun96** [comment]
@taoliu Hi Tao, here's the thing. In `conda` with `r-base 3.6.3`, if I don't specify the version, `bioconductor-annotationdbi 1.46.0` will be installed automatically, while `bioconductor-org.Hs.eg.db` requires `bioconductor-annotationdbi >= 1.47.0`. In this case, `conda build` will be successful, but `library(org.Hs.eg.db)` in R will fail. However, if I fix `bioconductor-annotationdbi =1.48.0`, conflicts will occur. So I downgraded `r-base` to `3.6.2`. Now I'm testing `conda` with `r-base 3.6.2`. If there's no problem, I will push the new `meta.yaml` here.

**Comment by taoliu** [comment]
@DongqingSun96 Is `bioconductor-org.Hs.eg.db` explicitly defined in `meta.yml` for conda? Is  `org.Hs.eg.db` mentioned in DESCRIPTION for R package? I don't see `AnnotationDbi` defined in DESCRIPTION as a dependency for MAESTRO R libraries either. Could we first get a *complete* list of dependencies?

**Comment by taoliu** [comment]
Now the travisCI conda building test (https://travis-ci.com/github/taoliu/MAESTRO/builds/173687273) is successful after 20 trials 🙈 . The new travisCI pipeline line will build a conda package based on local codes to a local channel, then try to install it. After that, it will test giggle/rabit/sinto/MAESTRO cmd/R loading MAESTRO and Seurat/R loading org.Hs.eg.db and org.Mm.eg.db. They all passed.

We still need some minimal testing data to go over the snakemake pipeline to make sure all steps can run without issue.

**Pull request merged**
